### ISSUE TITLE
Certain questions have wrong answers

### ISSUE THREAD

**Issue by R3gi** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#21]
I believe certain questions have incorrect answers.

29 "The practice of decomposing a requirement into failing tests is called"
❌ This is incorrect → Acceptance Test Driven Development.
✔ This is correct → Behavior Driven Development.

84 "A Development Team selects a set of Product Backlog Items for a Sprint Backlog with the intent to get the selected items "Done" by the end of the Sprint. Which three phrases best describe the purpose of a Definition of Done? (choose the best three answers)"
❌ This is incorrect → "It guides the Development Team in creating a forecast at the Sprint Planning."
✔ This is correct → "It tracks the percentage complete of a Product Backlog Item."

224 "Which is NOT true about Efferent Coupling?"
❌ This is incorrect → Classes with high efferent will affect other classes when changes are made.
✔ This is correct → Classes with high Efferent Coupling will receive the effects of changes or defects in other classes.

**Comment by danieldanielecki** [comment]
Hey @R3gi, thanks for the feedback.

29. I couldn't find anything regarding the decomposing requirement for BDD. In fact, it was also very hard to find for ATDD, but could find something. BDD & ATDD are very very similar, so this question can be consuming. In addition to that, https://www.browserstack.com/guide/tdd-vs-bdd-vs-atdd is the closest resource I could find explaining the difference, and based on that I'd still keep the current answer of `Acceptance Test Driven Development.`

84. `Percentage` and `tracking` isn't mentioned anywhere in the guide, so `It tracks the percentage complete of a Product Backlog Item.` is incorrect. The current answers are correct.

224. That's a tricky one, in general with high Efferent Coupling we're having problems with maintenance, to keep it simple. Those 2 answers could've been both correct, I feel. The closest I found was https://www.informit.com/articles/article.aspx?p=1561879&seqNum=3, and they literally write `Afferent coupling measures how many classes depend on a given class. Just as with efferent coupling, a good way to remember afferent is that classes with high afferent will affect other classes when changes are made.`, which means `Classes with high efferent will affect other classes when changes are made.` would be the correct answer if the question would ask for `Afferent Coupling`. With `Efferent coupling measures the number of classes on which a given class depends. A good way to remember efferent (versus afferent) is that classes with high efferent coupling will receive the effects of changes or defects in other classes.` and yes, you're correct :) fixed in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/2fe05ae1333394a20def695d8dffe5338b7f3b38

**Comment by danieldanielecki** [comment]
PS. The numbering doesn't work correctly, but in first answer was about question `29`, the second about `84`, and the last about `224`.
