### ISSUE TITLE
Wrong answer on "Which statements describe why automated builds are important?"

### ISSUE THREAD

**Issue by intoinside** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#6]
![image](https://user-images.githubusercontent.com/8144124/187475512-c8a520d1-d56b-4e23-ad0a-3f593310b599.png)

In this question, correct answers are:
- They allow frequent validation of the unit of software being worked on, ensuring it remains in a potentially shippable state.
- The build process is clearly defined and scripted, making it easy consistent and repeatable.
- They support continuous integration.

Automatic build cannot ensure that product remains bug free.

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/4914288ba5ad5f08a8003f2742562a6dec40e589.

Kindly please use [Pull Requests (PR)](https://github.com/Ditectrev/Professional-Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/pulls) for a quick fixes next time ;-)
